[book]
title = "Lifetime Variance Example"
authors = ["Rain"]
language = "en"
multilingual = false
src = "src"
theme = "theme"
description = "Rust tutorial for lifetime variance, using code examples."


[output.html]
git-repository-url = "https://github.com/sunshowers-code/lifetime-variance"
edit-url-template = "https://github.com/sunshowers-code/lifetime-variance/edit/main/{path}"
site-url = "https://lifetime-variance.sunshowers.io"
additional-css = ["additional/ferris.css"]
additional-js = ["additional/ferris.js"]
